language: python

os: linux

arch: arm64-graviton2

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev
  - nightly

jobs:
  allow_failures:
    - python: 3.10-dev
    - python: nightly

before_install:
  - python --version
  - pip install -U pip

script:
  - sh unittest.sh
